# Generated by Django 3.2.7 on 2021-09-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempts',
            name='image',
            field=models.ImageField(upload_to='uploaded_temp_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_lock_img',
            field=models.ImageField(blank=True, null=True, upload_to='security_images'),
        ),
    ]
