# Generated by Django 3.2.7 on 2021-09-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210925_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginAttempts',
            new_name='LoginAttempt',
        ),
    ]
