# Generated by Django 3.2.7 on 2021-09-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_loginattempts_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
