# Generated by Django 3.2.7 on 2021-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210928_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='blob_img',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='image',
            field=models.ImageField(default=None, upload_to='uploaded_temp_images'),
            preserve_default=False,
        ),
    ]
